# Your local subnet IP for the smart bulb. Usually you can find this info from your router.
Devices:
  Kitchen: "10.75.100.137"
  LivingRoom: "10.75.100.133"
  LivingRoomAux: "10.75.100.134"
  DiningRoom: "10.75.100.136"

  OfficeTop: "10.75.100.141"
  Office2: "10.75.100.142"
  Office3: "10.75.100.144"

  Porch: "10.75.100.146"

# [Hue, Saturation] values
# See https://web.cs.uni-paderborn.de/cgvb/colormaster/web/color-systems/hsv.html
Colors:
  Red: [0, 75]
  Blue: [159, 75]
  Orange: [12,85]
  Green: [129, 75]
  Violet: [307, 75]

# One-time routines should have start times only
# Continuous routines should have an end
# For Sunrise schedules, you can use Sunrise or Sunset and 
# then +/- a float in hours to offset, if desired.
Schedules:
  BeforeSunset:
      Start: Sunset-1.5
      End:
  Sunset:
      Start: Sunset
      End:
  AfterSunset:
      Start: Sunset+1
      End:
  LateNight:
      Start: Sunrise-4
      End:
  Sunrise:
      Start: Sunrise
      End:
  StartWorkday:
      Start: '08:30'
      End:
  Overnight:
      Start: Sunset
      End: Sunrise

Routines:
  - Schedule: StartWorkday
    Devices:
      OfficeTop:
        Type: on
        Colors: []
        Brightness: 50
        Interval: 5
      Office2:
        Type: on
        Colors: []
        Brightness: 40
        Interval: 5
      Office3:
        Type: on
        Colors: []
        Brightness: 70
        Interval: 5

  - Schedule: BeforeSunset
    Devices:
      Kitchen:
        Type: on
        Colors: []
        Brightness: 40
        Interval: 10
      LivingRoom:
        Type: on
        Colors: []
        Brightness: 20
        Interval: 15
      LivingRoomAux:
        Type: on
        Colors: []
        Brightness: 50
        Interval: 15
      OfficeTop:
        Type: on
        Colors: []
        Brightness: 30
        Interval: 15
      Office2:
        Type: on
        Colors: []
        Brightness: 20
        Interval: 15
      Office3:
        Type: on
        Colors: []
        Brightness: 45
        Interval: 15

  - Schedule: Sunset
    Devices:
      Porch:
        Type: turn_on
        Colors: []
        Brightness: 100
        Interval: 15
      Kitchen:
        Type: set_brightness
        Colors: []
        Brightness: 20
        Interval: 10
      LivingRoom:
        Type: set_brightness
        Colors: []
        Brightness: 10
        Interval: 10

  - Schedule: LateNight
    Devices:
      Porch:
        Type: set_brightness
        Colors: []
        Brightness: 25
        Interval: 10
      LivingRoomAux:
        Type: off
        Colors: []
        Brightness:
        Interval: 10

  - Schedule: Sunrise
    Devices:
      Porch:
        Type: off
        Colors: []
        Brightness:
        Interval: 10

# Example of a continuous/siren routine that rotates three lights
# independent of each other but in parallel.

#  - Schedule: Schedule2
#    Devices:
#      OfficeTop:
#        Type: smooth_rotate
#        Colors: [Violet, Red, Blue, Orange]
#        Brightness: 80
#        Interval: 1 
#      Office2:
#        Type: smooth_rotate
#        Colors: [Orange, Violet, Red, Blue]
#        Brightness: 80
#        Interval: 1 
#      Office3:
#        Type: smooth_rotate
#        Colors: [Blue, Orange, Violet, Red]
#        Brightness: 80
#        Interval: 1 