Bulbs:
  OfficeTop: "10.75.100.141"
  Office2: "10.75.100.142"
  Office3: "10.75.100.144"
  Porch: "10.75.100.146"

Colors:
  Red: [0, 100, 36]
  Blue: [159, 50, 26]
  Orange: [12, 80, 53]

# Routine must be ordered from 0-X without skipping
# Colors and Brightness can be left blank
Routines:
  - Type: smooth_rotate
    Bulbs: [Office3]
    Colors: [Blue, Orange, Red]
    Brightness:
    Interval: 4
  
  - Type: smooth_rotate
    Bulbs: [Office2]
    Colors: [Orange, Red, Blue]
    Brightness:
    Interval: 4

  - Type: smooth_rotate
    Bulbs: [OfficeTop]
    Colors: [Red, Blue, Orange]
    Brightness:
    Interval: 4