Bulbs:
  OfficeTop: "10.75.100.141"
  Office2: "10.75.100.142"
  Office3: "10.75.100.144"
  Porch: "10.75.100.146"

# Hue, Saturation values
# See https://web.cs.uni-paderborn.de/cgvb/colormaster/web/color-systems/hsv.html
Colors:
  Red: [0, 100]
  Blue: [159, 100]
  Orange: [12, 100]
  Green: [129, 100]
  Violet: [307, 100]

Schedules:
  Overnight:
    - Start: Sunset
      End: Sunrise
  Schedule2:
    - Start:
      End:
  Schedule3:
    - Start:
      End:

# Routine must be ordered from 0-X without skipping
# Colors and Brightness can be left blank
Routines:
  - Type: hard_rotate
    Bulbs: [Office2, Office3]
    Colors: [Red, Blue, Green, Orange] 
    Brightness: 10
    Interval: 2
    Schedule:

  - Type: hard_rotate
    Bulbs: [OfficeTop]
    Colors: [Blue, Orange, Violet, Red]
    Brightness: 20
    Interval: 2
    Schedule: