# Your local subnet IP for the smart bulb. Usually you can find this info from your router.
Bulbs:
  OfficeTop: "10.75.100.141"
  Office2: "10.75.100.142"
  Office3: "10.75.100.144"
  Porch: "10.75.100.146"

# [Hue, Saturation] values
# See https://web.cs.uni-paderborn.de/cgvb/colormaster/web/color-systems/hsv.html
Colors:
  Red: [0, 75]
  Blue: [159, 75]
  Orange: [12,85]
  Green: [129, 75]
  Violet: [307, 75]

# Not yet implemented!
Schedules:
  Overnight:
      Start: '22:00'
      End: '6:00'
  Schedule2:
      Start: '2:00'
      End: '12:30'
#  Schedule3:
#      Start:
#      End:

# See readme.MD for details
Routines:
  - Name: Routine 1
    Type: smooth_rotate
    Bulbs: [OfficeTop]
    Colors: [Violet, Red, Blue, Orange]
    Brightness: 80
    Interval: 3
    Schedule: Overnight

  - Name: Routine 2
    Type: smooth_rotate
    Bulbs: [Office2]
    Colors: [Orange, Violet, Green, Blue] 
    Brightness: 60
    Interval: 3
    Schedule: Overnight

  - Name: Routine 3
    Type: smooth_rotate
    Bulbs: [Office3]
    Colors: [Red, Orange, Violet, Red] 
    Brightness: 80
    Interval: 3
    Schedule: Schedule2