# Your local subnet IP for the smart bulb. Usually you can find this info from your router.
Bulbs:
  OfficeTop: "10.75.100.141"
  Office2: "10.75.100.142"
  Office3: "10.75.100.144"
  Porch: "10.75.100.146"

# [Hue, Saturation] values
# See https://web.cs.uni-paderborn.de/cgvb/colormaster/web/color-systems/hsv.html
Colors:
  Red: [0, 75]
  Blue: [159, 75]
  Orange: [12,85]
  Green: [129, 75]
  Violet: [307, 75]

Schedules:
  Overnight:
      Start: '20:00'
      End: '05:00'
  BeforeSunset:
      Start: '21:28'
      End: '21:29'
  Sunset:
      Start: '17:46'
      End:
  AfterSunset:
      Start:
      End:

# See readme.MD for details
Routines:
  - Schedule: Sunset
    Devices:
      OfficeTop:
        Type: power_on
        Brightness: 90
        Interval: 15

#  - Schedule: Schedule2
#    Devices:
#      OfficeTop:
#        Type: smooth_rotate
#        Colors: [Violet, Red, Blue, Orange]
#        Brightness: 80
#        Interval: 1 
#      Office2:
#        Type: smooth_rotate
#        Colors: [Orange, Violet, Red, Blue]
#        Brightness: 80
#        Interval: 1 
#      Office3:
#        Type: smooth_rotate
#        Colors: [Blue, Orange, Violet, Red]
#        Brightness: 80
#        Interval: 1 