FROM python:3.11.5-slim

EXPOSE 8008

COPY config.yaml controller.py presents.yaml requirements.txt, webhook.py /app/

WORKDIR /app

RUN python -m pip install --upgrade pip \
&& pip install -r requirements.txt

CMD ["uvicorn", "webhook:app", "--host", "0.0.0.0", "--port", "8008"]